pipeline:
  ssh:
    image: appleboy/drone-ssh
    host: 103.109.37.178
    username: root
    password: tuanhung0601
    port: 22
    script:
      - cd /usr/share/nginx/html/
      - git pull origin master
      - mkdir cainaylatest
       
